name: ucvm-ci

on:
  push:
    branches: [ toPython3 ]

jobs:
  ucvm-build-cvmh:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/UCVMC" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/TARGET" >> $GITHUB_ENV
    - uses: actions/checkout@v2
      with: 
        ref: toPython3
    - name: locate aclocal
      run: which aclocal
    - name: build ucvm with cvmh
      run: ./ci/ucvm-build-cvmh.sh 
      shell: bash
